-- auto-generated definition
create table services
(
    id                  int generated by default as identity
        primary key,
    user_id             int                        not null,
    title               varchar(255)               not null,
    category_id         int                        not null,
    price               decimal(12, 2)             null,
    currency_id         int                        null,
    minbatch            decimal(12, 2)             null,
    maxbatch            decimal(12, 2)             null,
    unit_id             int                        null,
    city_id             int                        null,
    cover_image_file_id int                        null,
    rating              decimal(3, 2)              null,
    active              boolean      default true  not null,
    view_count          int          default 0     not null,
    approval_passed     boolean      default false not null,
    created_at          timestamp                  null,
    updated_at          timestamp                  null,
    default_language    varchar(5)                 null,
    ratingkeys          varchar(255) default ''    not null,
    price_id            int                        null,
    price_id_to         int                        null,
    status              smallint     default 2     null,
    hide_in_latest      boolean      default false null,
    link_video_id       int                        null,
    term                int                        null,
    term_unit           varchar(5)   default 'D'   null,
    system_tags         varchar(255)               null,
    source              varchar(80)                null,

    constraint service_ufk
        foreign key (user_id) references users (id)
            on delete cascade
)

