create table contractor_checks
(
    id             int generated by default as identity,
    partner_id     int       not null,
    reg_number     varchar(32),
    name           varchar(255),
    dt_begin       date,
    dt_end         date,
    country_code   varchar(10),
    company_type   varchar(255),
    current_status varchar(255),
    created_at     timestamp not null,
    updated_at     timestamp null
);