create table partners
(
    id           int generated by default as identity
        primary key,
    alias        varchar(16)           not null,
    logo         varchar(128)          null,
    icon         varchar(128)          null,
    offer_url    varchar(128)          null,
    have_cabinet boolean default false not null,
    "order"        int                   not null,
    published    boolean default false not null,
    created_at   timestamp             not null,
    updated_at   timestamp             null,
    constraint alias
        unique (alias)
);

comment on column partners.alias is 'Алиас, техническое имя на англ. языке';
comment on column partners.logo is 'Путь до логотипа';
comment on column partners.icon is 'Путь до иконки';
comment on column partners.offer_url is 'Ссылка на договор оферты';
comment on column partners.have_cabinet is 'Партнер может иметь Кабинет партнера';
comment on column partners."order" is 'Порядок';
comment on column partners.published is 'Опубликовано: 0 - нет, 1 - да';
comment on column partners.created_at is 'Дата создания';
comment on column partners.updated_at is 'Дата обновления';
